# Generated by Django 3.2.12 on 2022-03-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderDetails',
            new_name='OrderDetails',
        ),
    ]
