# Generated by Django 3.2.12 on 2022-03-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_oderdetails_orderdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='oder',
            new_name='order',
        ),
    ]
