# Generated by Django 3.2.12 on 2022-03-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_oder_orderdetails_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('total_money', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('total_money', models.FloatField(blank=True, default=0, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_statistics', to='product.product')),
            ],
        ),
    ]
