# Generated by Django 3.2.12 on 2022-03-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_customerstatistics_productstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerstatistics',
            name='timestamp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='productstatistics',
            name='timestamp',
            field=models.FloatField(null=True),
        ),
    ]
