# Generated by Django 3.2.12 on 2022-03-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220318_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=10, null=True, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=8, null=True)),
                ('number_of_transactions', models.IntegerField(default=0, null=True)),
                ('total_money', models.FloatField(default=0, null=True)),
                ('attachment_level', models.CharField(choices=[('Level_1', 'Level_1'), ('Level_2', 'Level_2'), ('Level_3', 'Level_3'), ('Level_4', 'Level_4')], max_length=8, null=True)),
                ('age', models.IntegerField(default=20, null=True)),
            ],
        ),
    ]
